Mini Color TFT with Joystick FeatherWing
adafruit/Adafruit_CircuitPython_FeatherWing pull request #38
Opened 2019-04-10 05:40 UTC by makermelissa

Here's my take on a Mini TFT with Joystick FeatherWing Library. This one is complete with simpletest and documentation changes.

2019-04-10 12:19 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        self._button_mask = const((1 << BUTTON_RIGHT) |
this ``const()`` does nothing

2019-04-10 12:22 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        self._button_mask = const((1 << BUTTON_RIGHT) |
this could be a class attribute, not an object attribute

2019-04-10 12:22 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        return self._ss.digital_read_bulk(self._button_mask)
I wonder if there could be some caching here, so that if we want to check 5 different buttons, we don't make 5 separate calls to the seesaw.

2019-04-10 12:34 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        return self._display
Is there any reason for this to be a property and not a straightforward attribute?

2019-04-10 12:34 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        return self._ss.digital_read_bulk(self._button_mask)
What if there was just a ``buttons`` property, that would return a named tuple of True/False values for all the buttons at once? Then you could do:

```python
buttons = wing.buttons
if buttons.reight:
    ...
elif buttons.left:
    ...
```

2019-04-10 14:33 UTC, hexthat commented
with this how do you adjust the brightness?

2019-04-10 14:52 UTC, makermelissa commented
Good point @hexthat. I’ll add that.

2019-04-10 14:53 UTC, makermelissa commented
Thanks @deshipu for reviewing this. I’ll make some changes tonight.

2019-04-10 14:59 UTC, deshipu commented
I'm playing with PyBadge now, and I came up with this code for the buttons for it:

```python
import board
import digitalio
import bitbangio
import time
import collections


Buttons = collections.namedtuple('Buttons',
                                 'left up down right select start a b')


class PyBadgeButtons:
    def __init__(self):
        self._bus = bitbangio.SPI(clock=board.BUTTON_CLOCK,
                                  MISO=board.BUTTON_OUT)
        while not self._bus.try_lock():
            pass
        self._bus.configure(polarity=1, phase=1)
        self._latch = digitalio.DigitalInOut(board.BUTTON_LATCH)
        self._latch.switch_to_output(value=0)
        self._buffer = bytearray(1)

    @property
    def pressed(self):
        self._latch.value = 1
        self._bus.readinto(self._buffer)
        self._latch.value = 0
        pressed = self._buffer[0]
        return Buttons(*[bool(pressed & (1 << button)) for button in range(8)])


buttons = PyBadgeButtons()
while True:
    print(buttons.pressed)
    time.sleep(1)
```

I think we could use something very similar here.

2019-04-11 05:07 UTC, makermelissa commented
Ok, backlight added, unnecessary const() removed, display is an attribute, and buttons returned as named tuple so they are only read once per loop instead of 7 times.

2019-04-11 09:01 UTC, deshipu requested changes
Looks good, some nit-picks.

2019-04-11 09:01 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +                (1 << BUTTON_B))
You can you put this on the class, like this:

```python
class MiniTFTFeatherWing:
    _button_mask = ((1 << BUTTON_RIGHT) |
￼                 (1 << BUTTON_DOWN) |
￼                 (1 << BUTTON_LEFT) |
￼                 (1 << BUTTON_UP) |
￼                 (1 << BUTTON_SEL) |
￼                 (1 << BUTTON_A) |
￼                 (1 << BUTTON_B))

    def __init_(self, ...
```

2019-04-11 09:01 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +        buttons = namedtuple("Buttons", "up down left right a b select")
Can you move this outside the class, where the constants are, so that users have access to it? Also, since it's a type, it should start with upper case letter.

2019-04-11 09:01 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +                       select=(not button_values & (1 << BUTTON_SEL)))
You can write this as:
```python
return Buttons(*[not button_values & (1 << button) for button in
                 (BUTTON_UP, BUTTON_DOWN, BUTTON_LEFT, BUTTON_RIGHT, BUTTON_A, BUTTON_B,BUTTON_SEL)])
```

2019-04-12 00:52 UTC, makermelissa commented
Ok, requested changes implemented.

2019-04-12 08:52 UTC, deshipu commented on adafruit_featherwing/minitft_featherwing.py
> +                (1 << BUTTON_B))
Could you do this as well? I think making it a property is wasteful.

2019-04-12 19:22 UTC, deshipu approved these changes

2019-04-12 19:23 UTC, merged

2019-04-12 19:23 UTC, deshipu commented
Thank you, it looks great!