Add typehints
adafruit/Adafruit_CircuitPython_FeatherWing pull request #74
Opened 2021-11-02 01:53 UTC by tekktrik

Shout out to whoever added those Sphinx markups, you made life much easier!

2021-11-02 17:50 UTC, tekktrik commented
Meant to tag this as resolving issue #72

2021-11-02 20:24 UTC, jepler commented
> Meant to tag this as resolving issue #72

I added text to the initial comment so that the issue would be linked.

2021-11-02 20:32 UTC, tekktrik commented
Missed that, thanks!

2021-11-05 19:11 UTC, tekktrik commented
I know there was a patch for upgrading pylint, but I can't seem to get it, is that something I should do for this?

2021-11-05 19:33 UTC, kattni commented
@tekktrik You don't need to do anything to upgrade Pylint on this repo, it happens behind the scenes. I've rerun the jobs - a number of the failures are a check we are disabling separately. I will rerun the jobs after that, and then you are welcome to take care of the rest of the linting issues in the repo (as per https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/pull/75/files) and we can close Dylan's PR in place of this one. Otherwise, I need to merge Dylan's PR, and then you have to update this one to match anyway. 

Are you up for linting this? You would need to update the imports, and disable `,duplicate-code` exactly like I explained on Discord for the other repo. Please ignore the `unspecified-encoding` check, as it should be disabled globally in a bit here.

2021-11-05 21:33 UTC, tekktrik commented
Definitely up for linting!

2021-11-05 21:39 UTC, tekktrik commented
Just merged that linting branch into mine

2021-11-05 21:42 UTC, tekktrik commented
I see where to add the `,duplicate-code` comment, is it because the PATCH failed?

2021-11-05 21:43 UTC, tekktrik commented
Nevermind that, working on it now!

2021-11-05 22:12 UTC, tekktrik commented
Changes from #75 incorporated!

2021-11-05 22:30 UTC, kattni requested changes
Thanks so much! One more thing below.

2021-11-05 22:30 UTC, kattni commented on examples/featherwing_tft35_simpletest.py
> +    with open(  # pylint: disable=unspecified-encoding
Please remove this `pylint: disable=` as we've added it globally. Thanks!

2021-11-05 22:30 UTC, kattni commented on examples/featherwing_tft35_simpletest.py
> +    with open(  # pylint: disable=unspecified-encoding
Same!

2021-11-05 22:37 UTC, tekktrik commented
Oh nice catch!  Removed!

2021-11-05 22:41 UTC, kattni approved these changes
This is great! Thanks for sticking through it, @tekktrik!

2021-11-05 22:41 UTC, merged

2021-11-05 22:45 UTC, tekktrik commented
My pleasure!  Thanks for all the assistance on these!